#!/usr/bin/env php
<?php

use Application\Bootstrap;

// Register the auto loader
require __DIR__ . '/bootstrap/autoloader.php';

$bootstrap = new Bootstrap( 'cli','task' );

try {
	$bootstrap->run();
} catch ( Exception $e ) {
	fwrite( STDERR, PHP_EOL . $e->getMessage() . PHP_EOL );
	fwrite( STDERR, PHP_EOL . $e->getTraceAsString() . PHP_EOL . PHP_EOL );
	exit( 1 );
}
