<?php

namespace Application\Controllers;

use Application\Core\User;
use Phalcon\Mvc\View;

class IndexController extends ControllerBase {
	public function beforeExecuteRoute($dispatcher)
    {
        parent::beforeExecuteRoute($dispatcher); // TODO: Change the autogenerated stub
    }

    public function helloWorldAction() {
		$this->view->disable();
		echo "Hello World";
	}
}

